### ISSUE TITLE
Cannot run first example

### ISSUE THREAD

**Issue by Obsidian-user** [mikeasilva/simplegraphdb#1]
Hi,

When I try to run the first example on my computer, running macOS 13.4, I get the following error:

```
apple <- "apple.sqlite"
initialize(apple)
## Warning: cannot open file './tests/schema.sql': No such file or directoryError in file(con, "rb") : cannot open the connection
```

I'm sure the fix is simple but, as a beginner, I haven't yet got the skills to solve the problem, and without a fix I'm sure other beginners may bounce 

### Attempts on solving the issue

I assume there may be an issue with the default path. As far as I'm aware, I've given R & RStudio the relevant permissions to access the file in macOS. I'm unsure how to create a blank "sqlite" file otherwise I would test that. Using SQLite, the file extension of the generated file is `.db`, so unsure how to adapt the `initialize` function to accommodate this.

I've tried running the example through the help file in RStudio, but the commands are commented, so do not produce an output.

Thanks for your work on this project.

**Comment by mikeasilva** [comment]
Clone the repository and set your working directory to the repository.
